version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: opencbanking-pwa:0.0.2
        container_name: opencbanking-pwa
        ports:
            - '3000:3000' # map host 3000 to container port 3000
        environment:
            - NODE_ENV=production
            - PORT=3000
            - HOSTNAME=0.0.0.0
            - NEXT_TELEMETRY_DISABLED=1
        restart: unless-stopped

        networks:
            - app-network

networks:
    app-network:
        driver: bridge
